---
- name: Configure soft limk
  hosts: all
  become: yes
  become_user: root
  tasks:
        - name: Create symbolic link 
                file:
                        src: "{{SOURCE_FOLDER}}"
                        dest: "/opt/application/i99/SYMLINK"
                        state: link
